### ISSUE TITLE
Camel plugin freezes IDEA performing IO on EventDispatchThread

### ISSUE THREAD

**Issue by robabod** [camel-tooling/camel-idea-plugin#381] opened 2018-02-09 11:48 UTC
After installing camel-idea-plugin 0.4.6 in IntelliJ IDEA 2017.3.2, I began experiencing lockups in IDEA of anything up to a minute (where IDEA was unresponsive and appeared not to be busy).

The automatic threadDumps suggest that the camel-idea-plugin is performing IO on the Event Dispatch thread.

A similar issue was resolved in [IDEA 2017.3.3](https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+2017.3.3+Release+Notes), but the issue still existed when I upgraded to IDEA 2017.3.4.

Note that when I start up it fails to find the camel catalog for the version of Camel I am using (2.17), and defaults to using the catalog for the latest version.

Below is a stack trace of the EDT from one of the threadDumps:
```
"AWT-EventQueue-0 2017.3.2#IU-173.4127.27 IDEA, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_152-release-1024-b8 [WriteAccessToken]" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:930)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:791)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:876)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:869)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:868)
	at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:841)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:565)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:554)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:519)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:484)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:214)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at org.apache.camel.idea.service.CamelService.loadComponentProperties(CamelService.java:483)
	at org.apache.camel.idea.service.CamelService.addCustomCamelComponentsFromDependency(CamelService.java:402)
	at org.apache.camel.idea.service.CamelService.scanForCamelDependencies(CamelService.java:328)
	at org.apache.camel.idea.CamelProjectComponent$1.rootsChanged(CamelProjectComponent.java:90)
	at sun.reflect.GeneratedMethodAccessor474.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:449)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:410)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:399)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy225.rootsChanged(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$AppListener.writeActionFinished(ProjectRootManagerComponent.java:327)
	at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy5.writeActionFinished(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.f(ApplicationImpl.java:1387)
	at com.intellij.openapi.application.impl.ApplicationImpl.c(ApplicationImpl.java:1212)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$500(ApplicationImpl.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$WriteAccessToken.finish(ApplicationImpl.java:1248)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:185)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$472/902838668.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$331/2143056213.run(Unknown Source)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by davsclaus** [comment] 2018-03-03 09:33
Do you have any http proxy or anything that can cause issue downloading from maven central? 

The plugin will attempt to download camel-catalog JAR from the version you use. You can try to download that yourself and install in your local m2 repo so the plugin should not download the JAR over the internet.

**Comment by davsclaus** [comment] 2018-03-03 09:34
AFAIR there is also a setting you can turn on|off to allow downloading the camel-catalog in the plugin in case you want to force it to not attempt to download the version over the internet

**Comment by davsclaus** [comment] 2018-03-03 09:34
To download camel-catalog you can add it as dependency to your pom.xml and let Maven itself download it for you.

**Comment by robabod** [comment] 2018-03-13 12:45
Hi, sorry for delay replying.
Yes, we do have a firewall, however we have a local Nexus server which can "go outside" for us.  But i did have downloading the camel-catalog disabled in the settings.
I don't have the plugin installed currently, but I'll load it up again and try installing the catalog locally to see if it fixes the freeze problem - it would at least narrow down the issue.

**Comment by davsclaus** [comment] 2019-07-25 05:35
Okay this is a duplicate of #459 so lets close this

**Closed by davsclaus** 2019-07-25 05:35 UTC
Labels: bug
